### ISSUE TITLE
Add "throws" to sequence of values closure

### ISSUE THREAD

**Issue by skywalkerdude** [birdrides/mockingbird#111]
Would it be possible to have the closure `() -> ReturnType` include throwing functions? So like the first time you call a method, it returns something but the second time it throws an error, or vice versa

Reference: https://github.com/birdrides/mockingbird#sequence-of-values-0120
```
public func sequence<FunctionType, ReturnType>(of lazyValues: (() -> ReturnType)...)
  -> StubImplementation<FunctionType, ReturnType> {
    var index = 0
    let implementation: () -> ReturnType = {
      let value = lazyValues[index]()
      if index+1 < lazyValues.count { index += 1 }
      return value
    }
    return StubImplementation<FunctionType, ReturnType>(handler: implementation, callback: nil)
}```

**Comment by andrewchang-bird** [comment]
Thanks for bringing this up. For 0.13 I’ll look into migrating lazily computed value sequences into full closure stubs, which would allow for throwing errors.
