### ISSUE TITLE
Autogenerated files fail for non-default product name

### ISSUE THREAD

**Issue by cnotethegr8** [birdrides/mockingbird#129]
## Description

In the build settings I have changed the 'Product Name' from `$(TARGET_NAME)` to `$(PROJECT_NAME)` for reasons outside the scope of this issue. The autogenerated files create 2 issues related to this.

1. Importing my app creates an issue since the statement says `import #target_name#` instead of `import #project_name#`. This issue I was able to resolve by passing `--disable-module-import`.
2. All generated classes inherit and conform to something like, 
    `public class SomeClass: TargetName.SomeClass, MockingBird.Mock`,
    which creates the issue of 'this module doesn't exist'.

Since this is a design issue and not a bug, I will leave out code examples unless requested.

Are you able to use the `Product Name` value from the build settings? By doing this, you would be using the actual value and not assuming the default value, which would fix this problem.

**Comment by andrewchang-bird** [comment]
Hi Corey, thanks for filing! Mockingbird [pulls the value](https://github.com/birdrides/mockingbird/blob/23f49d261be0d80702abce11b68fc4ff76a4a85f/MockingbirdGenerator/Parser/Project/PBXTarget%2BTargetConformance.swift#L26) from `PRODUCT_MODULE_NAME` unless it’s not set. Does setting the target’s product module name to `$(PRODUCT_NAME)` or `$(PROJECT_NAME)` solve the import issue?

**Comment by cnotethegr8** [comment]
It still doesn't work when I make that change. I created a sample app which reproduces my issue. The setup of iOS and macOS replicates how my project is. If you look at the build setting (for either platform) you'll see the `PRODUCT_MODULE_NAME ` is set to `$(PROJECT_NAME)`. However when testing (⌘ + U) the generated files still show the target name with the error `Use of undeclared type 'MockingSampleApp_iOS'`.

Can you please take a look and let me know where my problem is?

https://github.com/cnotethegr8/MockingSampleApp

**Comment by andrewchang-bird** [comment]
Thanks for the sample, it looks like `PROJECT_NAME` is an implicit build setting from the Xcode build environment (similar to `TARGET_NAME`). I’ll fix this for 0.13, but in the meantime the workaround is to either use a literal value in `PRODUCT_MODULE_NAME` e.g. `MockingSampleApp` or add a user-defined build setting (Editor > Add Build Setting > Add User-Defined Setting) with the key `PROJECT_NAME` and a literal value.
