### ISSUE TITLE
Ignoring any files produces an empty generated file

### ISSUE THREAD

**Issue by nickcurran** [birdrides/mockingbird#13]
## Description
If I put even a single file in my .mockingbird-ignore, the generator will generate no mocks. 

## Example
My .mockingbird-ignore looks like this:

```
Locator.swift
SectionViewModel.swift
```

Resulting complete mocks file:
```
//
//  TableSideMocks.generated.swift
//  TableSide
//
//  Generated by Mockingbird v0.7.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import TableSide
import Foundation

```

If I remove the text from the ignore file, the mocks generate fine, although the ones in question don't compile.

## Environment

* Mockingbird CLI version - 0.7.0
* Xcode and macOS version - Xcode 11.1, macOS Catalina Beta
* Swift version - 5.1
* Installation method - SPM
* Unit testing framework - XCTest
* Does your project use `.mockingbird-ignore`? Yup. :D 

<img width="695" alt="Screen Shot 2019-10-28 at 5 25 50 PM" src="https://user-images.githubusercontent.com/1237097/67722742-02e69a80-f9a8-11e9-8c98-7785dcc01a4e.png">

**Comment by andrewchang-bird** [comment]
Thanks for the report! I’m not seeing this on my end using the `.mockingbird-ignore` E2E tests in `MockingbirdTestsHost`.

1. Where in your project is the ignore file located? 
2. Can you add the `--verbose` flag to your test target Generate Mockingbird Mocks script phase and post the build logs that start with `[DEBUG] Ignoring source path at`?

**Comment by nickcurran** [comment]
I'm not going to post the whole thing, because it looks like it's just a list of every file. It starts and ends with the following:

```
nick@faraday ~/workspace/sail/TableSide
:: mockingbird generate --targets 'TableSide' --support 'Test/Unit/Mocks' --outputs 'Test/Unit/Mocks/TableSideMocks.generated.swift' --disable-cache --verbose
[DEBUG] Using inferred Xcode project at /Users/nick/workspace/sail/TableSide/TableSide.xcodeproj
[DEBUG] Parse Xcode Project - Took 32.64 ms
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/UI/Tickets/TicketCell.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/Model/Transport/SailError.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/Model/Transport/Report.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/Services/Protocols/Repo.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/Model/Cached/Plu.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/Extensions/Dictionary+Extensions.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/UI/Startup/ServiceSettingsViewController.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/Model/Transport/TimeClock.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/UI/Components/MainButton.swift

...

[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/Model/Cached/Charge.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/Model/Cached/AutoCharge.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/Model/Transport/Split.swift
[DEBUG] Ignoring source path at /Users/nick/workspace/sail/TableSide/Model/Transport/Item.swift
[DEBUG] Extract Sources - Took 16.4 ms
[DEBUG] Found 0 source files and 0 dependency source files for target `TableSide`
[DEBUG] Parse Files - Took 0.03 ms
[DEBUG] Created 0 mockable types
[DEBUG] Process Types - Took 0.04 ms
[DEBUG] Render Mocks - Took 0.21 ms
Generated file to /Users/nick/workspace/sail/TableSide/Test/Unit/Mocks/TableSideMocks.generated.swift
[DEBUG] Write Files - Took 1.56 ms
[DEBUG] Run Program - Took 59.41 ms

```

**Comment by andrewchang-bird** [comment]
Hm, still unable to reproduce it in my environment (Mojave), which is also what the CI uses. It’s possible that the problem is specific to Catalina.

**Comment by andrewchang-bird** [comment]
Confirmed that this is specific to Catalina likely caused by a change in the `fnmatch` Darwin API.
