### ISSUE TITLE
Private initializer results in inaccessible initializer error in generated code

### ISSUE THREAD

**Issue by PaulWagener** [birdrides/mockingbird#130]
This example code:

```Swift
class Concrete {
    private init() {
    }
}
````

Results in this generated code:

````Swift

public final class ConcreteMock: Mocky.Concrete, Mockingbird.Mock {

  (...)

  fileprivate init(sourceLocation: Mockingbird.SourceLocation) {
    super.init()
    Mockingbird.checkVersion(for: self)
    self.sourceLocation = sourceLocation
  }
}
````

Because of the private initializer this results in an `'Concrete' initializer is inaccessible due to 'private' protection level` error.

Expected behavior would be compilable generated code. Probably by not creating a mock at all for such classes.

## Environment

* Mockingbird CLI version https://github.com/birdrides/mockingbird/commit/a246a830a288223a21c2c2065adf6f77845e66fd (current `master` as of this issues creation date)
* Xcode and macOS version `11.4.1`
* Swift version (`Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)`)
* Installation method `CocoaPods`

**Comment by andrewchang-bird** [comment]
Thanks for reporting! Looks like there’s some gaps in the system for detecting uninitializable classes.
