### ISSUE TITLE
"framework not found XCTest" Cannot build after installing using SPM

### ISSUE THREAD

**Issue by bopbi** [birdrides/mockingbird#131]
## Description

After install the mockingbird i cannot build the app

### Generator Bugs
just build the main module and it will failed, and the error will show

<img width="1051" alt="Screen Shot 2020-05-25 at 13 24 41" src="https://user-images.githubusercontent.com/131628/82784624-22389e00-9e8b-11ea-939f-39e4c0eb2f56.png">

## Environment

* Mockingbird CLI version 0.12.0
* Xcode 11.5 and macOS Catalina
* Swift version 5.2.4
* Installation method SPM

**Comment by bopbi** [comment]
update:

i able to make it run, by adding the XCtest on the main module like below:
<img width="858" alt="Screen Shot 2020-05-25 at 13 48 59" src="https://user-images.githubusercontent.com/131628/82786341-9d4f8380-9e8e-11ea-84d4-500543480c60.png">

is the step above necessary ?

**Comment by andrewchang-bird** [comment]
Hi Bobby, thanks for filing. Please try linking Mockingbird to a unit test target instead of the main app target. Here’s an example SPM Xcode project to help compare: [iOSMockingbirdExample-SPM](https://github.com/birdrides/mockingbird/tree/master/Examples/iOSMockingbirdExample-SPM)

**Comment by bopbi** [comment]
thanks for the response, previously i add mockingbird using xcode SPM, by default it target the main module

probably i missed that

**Comment by andrewchang-bird** [comment]
Thanks for the update! Closing this out.
