### ISSUE TITLE
Codable - 'required' initializer 'init(from:)' must be provided by subclass

### ISSUE THREAD

**Issue by Daedren** [birdrides/mockingbird#139]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

Mockingbird generates code that fails to compile when models that comply to Codable are involved.
Might be related to #87, as the error is the same, though that applied to Decodable. I can confirm Encodable alone compiles properly, just not both together.

The error shown from the example below:
`'required' initializer 'init(from:)' must be provided by subclass of 'CodModel'`

And the Xcode suggested hotfix is:
```
Insert '
  required init(from decoder: Decoder) throws {
      fatalError("init(from:) has not been implemented")
  }
'
```

1. A minimal example of the original source

<details>
  <summary>Click to expand example code</summary>

    
        public class CodModel: Codable {
            enum CodingKeys: String, CodingKey {
                case name
            }
            
            public var name: String
        
            public init(name: String) {
                self.name = name
            }
            
        }
        

</details>

2. The actual mocking code generated
<details>
  <summary>Click to expand generated code</summary>

        @testable import Mockingbird
        @testable import MockingbirdTesting
        import Foundation
        import Swift
        
        private var genericTypesStaticMocks = Mockingbird.Synchronized<[String: Mockingbird.StaticMock]>([:])
        
        // MARK: - Mocked CodModel
        
        public final class CodModelMock: MockingbirdTesting.CodModel, Mockingbird.Mock {
          static let staticMock = Mockingbird.StaticMock()
          public let mockingContext = Mockingbird.MockingContext()
          public let stubbingContext = Mockingbird.StubbingContext()
          public let mockMetadata = Mockingbird.MockMetadata(["generator_version": "0.12.2", "module_name": "MockingbirdTesting"])
          public var sourceLocation: Mockingbird.SourceLocation? {
            get { return stubbingContext.sourceLocation }
            set {
              stubbingContext.sourceLocation = newValue
              CodModelMock.staticMock.stubbingContext.sourceLocation = newValue
            }
          }
        
          public enum InitializerProxy {
            public static func initialize(`name`: String, __file: StaticString = #file, __line: UInt = #line) -> CodModelMock {
              let mock: CodModelMock = CodModelMock(name: `name`)
              mock.sourceLocation = SourceLocation(__file, __line)
              return mock
            }
          }
        
          // MARK: Mocked name
        
          override public var `name`: String {
            get {
              let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "name.get", arguments: [])
              return mockingContext.didInvoke(invocation) { () -> String in
                let implementation = stubbingContext.implementation(for: invocation)
                if let concreteImplementation = implementation as? () -> String {
                  return concreteImplementation()
                } else if let defaultValue = stubbingContext.defaultValueProvider.provideValue(for: (String).self) {
                  return defaultValue
                } else {
                  fatalError(stubbingContext.failTest(for: invocation))
                }
              }
            }
            set {
              let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "name.set", arguments: [ArgumentMatcher(newValue)])
              mockingContext.didInvoke(invocation)
              let implementation = stubbingContext.implementation(for: invocation)
              if let concreteImplementation = implementation as? (String) -> Void {
                concreteImplementation(newValue)
              } else {
                (implementation as? () -> Void)?()
              }
            }
          }
        
          public func getName() -> Mockingbird.Mockable<Mockingbird.VariableDeclaration, () -> String, String> {
            let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "name.get", arguments: [])
            return Mockingbird.Mockable<Mockingbird.VariableDeclaration, () -> String, String>(mock: self, invocation: invocation)
          }
        
          public func setName(_ newValue: @escaping @autoclosure () -> String) -> Mockingbird.Mockable<Mockingbird.VariableDeclaration, (String) -> Void, Void> {
            let arguments: [Mockingbird.ArgumentMatcher] = [Mockingbird.resolve(newValue)]
            let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "name.set", arguments: arguments)
            return Mockingbird.Mockable<Mockingbird.VariableDeclaration, (String) -> Void, Void>(mock: self, invocation: invocation)
          }
        
          // MARK: Mocked init(`name`: String)
        
          public required override init(`name`: String) {
            super.init(name: `name`)
            Mockingbird.checkVersion(for: self)
            let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "init(`name`: String) ", arguments: [Mockingbird.ArgumentMatcher(`name`)])
            mockingContext.didInvoke(invocation)
          }
        }
        
        /// Initialize an initializable class mock of `MockingbirdTesting.CodModel`.
        public func mock(_ type: MockingbirdTesting.CodModel.Type, file: StaticString = #file, line: UInt = #line) -> CodModelMock.InitializerProxy.Type {
          return CodModelMock.InitializerProxy.self
        }

</details>

## Environment

* Mockingbird CLI version (`mockingbird version`) 0.12.2
* Xcode and macOS version (are you running a beta?) 11.3.1
* Swift version (`swift --version`) 5.1.3
* Installation method (CocoaPods, Carthage, from source, etc) CocoaPods
* Unit testing framework (XCTest, Quick + Nimble, etc) XCTest
* Does your project use `.mockingbird-ignore`? No
* Are you using [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files)? No

**Comment by andrewchang-bird** [comment]
Hi Ricardo, thanks for reporting. I double-checked and it seems like this should be fixed in master by #93 which will go out in the 0.13 release next week. The workaround in the meantime is to explicitly declare `init(from:)` in `CodModel`.

If you still see this error in your project when using master please let us know. (You’ll need to point CocoaPods to the master branch and install the CLI from source `$ make setup-project && make install`.) Thanks!

**Comment by Daedren** [comment]
I can confirm I still see the same error in the master branch (Mockingbird now states it's version 0.12.0 though)

<details>
<summary>Generated code</summary>

```
//
//  MockingbirdTesting.generated.swift
//  MockingbirdTesting
//
//  Generated by Mockingbird v0.12.0.
//  DO NOT EDIT
//

@testable import Mockingbird
@testable import MockingbirdTesting
import Foundation
import Swift

private var genericTypesStaticMocks = Mockingbird.Synchronized<[String: Mockingbird.StaticMock]>([:])

// MARK: - Mocked CodModel

public final class CodModelMock: MockingbirdTesting.CodModel, Mockingbird.Mock {
  static let staticMock = Mockingbird.StaticMock()
  public let mockingContext = Mockingbird.MockingContext()
  public let stubbingContext = Mockingbird.StubbingContext()
  public let mockMetadata = Mockingbird.MockMetadata(["generator_version": "0.12.0", "module_name": "MockingbirdTesting"])
  public var sourceLocation: Mockingbird.SourceLocation? {
    get { return stubbingContext.sourceLocation }
    set {
      stubbingContext.sourceLocation = newValue
      CodModelMock.staticMock.stubbingContext.sourceLocation = newValue
    }
  }

  public enum InitializerProxy {
    public static func initialize(`name`: String, __file: StaticString = #file, __line: UInt = #line) -> CodModelMock {
      let mock: CodModelMock = CodModelMock(name: `name`)
      mock.sourceLocation = SourceLocation(__file, __line)
      return mock
    }
  }

  // MARK: Mocked name

  override public var `name`: String {
    get {
      let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "name.get", arguments: [], returnType: Swift.ObjectIdentifier((String).self))
      return mockingContext.didInvoke(invocation) { () -> String in
        let implementation = stubbingContext.implementation(for: invocation)
        if let concreteImplementation = implementation as? () -> String {
          return concreteImplementation()
        } else if let defaultValue = stubbingContext.defaultValueProvider.provideValue(for: (String).self) {
          return defaultValue
        } else {
          fatalError(stubbingContext.failTest(for: invocation))
        }
      }
    }
    set {
      let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "name.set", arguments: [ArgumentMatcher(newValue)], returnType: Swift.ObjectIdentifier(Void.self))
      mockingContext.didInvoke(invocation)
      let implementation = stubbingContext.implementation(for: invocation)
      if let concreteImplementation = implementation as? (String) -> Void {
        concreteImplementation(newValue)
      } else {
        (implementation as? () -> Void)?()
      }
    }
  }

  public func getName() -> Mockingbird.Mockable<Mockingbird.VariableDeclaration, () -> String, String> {
    let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "name.get", arguments: [], returnType: Swift.ObjectIdentifier((String).self))
    return Mockingbird.Mockable<Mockingbird.VariableDeclaration, () -> String, String>(mock: self, invocation: invocation)
  }

  public func setName(_ newValue: @escaping @autoclosure () -> String) -> Mockingbird.Mockable<Mockingbird.VariableDeclaration, (String) -> Void, Void> {
    let arguments: [Mockingbird.ArgumentMatcher] = [Mockingbird.resolve(newValue)]
    let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "name.set", arguments: arguments, returnType: Swift.ObjectIdentifier(Void.self))
    return Mockingbird.Mockable<Mockingbird.VariableDeclaration, (String) -> Void, Void>(mock: self, invocation: invocation)
  }

  // MARK: Mocked init(`name`: String)

  public required override init(`name`: String) {
    super.init(name: `name`)
    Mockingbird.checkVersion(for: self)
    let invocation: Mockingbird.Invocation = Mockingbird.Invocation(selectorName: "init(`name`: String) ", arguments: [Mockingbird.ArgumentMatcher(`name`)], returnType: Swift.ObjectIdentifier((Void).self))
    mockingContext.didInvoke(invocation)
  }
}

/// Initialize an initializable class mock of `MockingbirdTesting.CodModel`.
public func mock(_ type: MockingbirdTesting.CodModel.Type, file: StaticString = #file, line: UInt = #line) -> CodModelMock.InitializerProxy.Type {
  return CodModelMock.InitializerProxy.self
}
```
</details>

**Comment by andrewchang-bird** [comment]
I just noticed that you indicated you’re not using supporting source files. If you download the starter pack e.g. `$ mockingbird download starter-pack` in your project root and clear the previous `generated.swift` file, does that work?

**Comment by Daedren** [comment]
Ah you're right. Apologies, that part of the README went past me.
With the starter pack, the issue is fixed.
