### ISSUE TITLE
Unconsolidated parameter type for mock initialization

### ISSUE THREAD

**Issue by myihsan** [birdrides/mockingbird#154]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

When mocking non-generic types:

```swift
mock(SomeType.self)
```

When mocking generic types:

```swift
mock(SomeTypeMock<Int>.self)
```

And this difference seems undocumented.

## Proposal

For a non-protocol generic type:

```swift
public func mock<T>(_ type: ModelName.SomeGenericClass<T>.Type, file: StaticString = #file, line: UInt = #line) -> SomeGenericClassMock<T>
```

It's alright to code this way for a non-protocol generic type. But we can't do the same thing for an associated type required protocol. Luckily, there is a tricky way to solve this problem.

```swift
enum AssociatedTypesRequiredProtocol<T> {}
public func mock<T>(_ type: AssociatedTypesRequiredProtocol<T>.Type, file: StaticString = #file, line: UInt = #line) -> AssociatedTypesRequiredProtocolMock<T>
```

But it may seem odd in Swift when a user codes something like below:

```swift
mock(SomeProtocol<Int>.self)
```

**Comment by andrewchang-bird** [comment]
Thanks for putting this proposal together! I don’t see any downsides for class mocks and think it makes sense to unify the protocol mocking API despite the potential for ambiguity from shadowing the original type. #157 adds this behavior and should go out in the 0.15 release.
