### ISSUE TITLE
Generated code of a generic type is always in the form of thunk stubs

### ISSUE THREAD

**Issue by myihsan** [birdrides/mockingbird#155]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

When we mocking a generic type:

```swift
mock(SomeGenericTypeMock<Int>.self)
```

The name we are using to mock–`"SomeGenericTypeMock<Int>"` is not equal to the name of the original type name–`"SomeGenericType<T>"`, so Mockingbird can't detect that we are mocking this type.

## Proposal

#154 may solve the `Mock` part.
For the type placeholders part, we may have to erase them before checking the name. 

```swift

if mockableType.requiresGenericInitializer {
    guard let regex = try? NSRegularExpression(pattern: "<.*>") else { return true }
    let comparableTypeName: (String) -> String = { typeName in
        let comparableTypeName = NSMutableString(string: typeName)
        regex.replaceMatches(in: comparableTypeName, range: NSRange(location: 0, length: typeName.count), withTemplate: "")
        return comparableTypeName as String
    }
    let comparableTypeNames = typeNames.map(comparableTypeName)
    return comparableTypeNames.contains(comparableTypeName(mockableType.fullyQualifiedName)) ||
        comparableTypeNames.contains(comparableTypeName(mockableType.fullyQualifiedModuleName))
} else {
    return typeNames.contains(mockableType.fullyQualifiedName) ||
        typeNames.contains(mockableType.fullyQualifiedModuleName)
}
```

**Comment by andrewchang-bird** [comment]
Thanks for flagging this, Jierong! #156 should fix generic type thunk stub handling which I’m targeting for the upcoming 0.15 August release.

**Comment by myihsan** [comment]
Thanks! 👍
I didn't notice `removingGenericTyping` exists.
