### ISSUE TITLE
dyld: lazy symbol binding failed: can't resolve symbol _swiftparse_syntax_structure_versioning_identifier? 

### ISSUE THREAD

**Issue by ratkins** [birdrides/mockingbird#176]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

We're getting the following error on CI, running our tests against a simulator (but not locally):

```
/bin/sh -c /Users/runner/work/1/output/test/build.obj/XXXX.build/Dev-iphonesimulator/XXXXTests.build/Script-D2484978880008EAC85DCA93.sh
dyld: lazy symbol binding failed: can't resolve symbol _swiftparse_syntax_structure_versioning_identifier in /Users/runner/work/1/s/Pods/MockingbirdFramework/mockingbird because dependent dylib #3 could not be loaded
dyld: can't resolve symbol _swiftparse_syntax_structure_versioning_identifier in /Users/runner/work/1/s/Pods/MockingbirdFramework/mockingbird because dependent dylib #3 could not be loaded
/Users/runner/work/1/output/test/build.obj/XXXX.build/Dev-iphonesimulator/XXXXTests.build/Script-D2484978880008EAC85DCA93.sh: line 7:  8902 Abort trap: 6           ${SRCROOT}/Pods/MockingbirdFramework/mockingbird generate --targets 'XXXX' 'XXXXCore' --outputs "${SRCROOT}/MockingbirdMocks/XXXXTests-XXXXMocks.generated.swift" "${SRCROOT}/MockingbirdMocks/XXXXTests-XXXXCoreMocks.generated.swift" --support "${SRCROOT}/MockingbirdSupport"
Command PhaseScriptExecution failed with a nonzero exit code
```
## Environment

* Mockingbird CLI version (`mockingbird version`) `0.16.0`
* Xcode and macOS version (are you running a beta?) `11.7`, `10.15.7`
* Swift version (`swift --version`) `Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)`
* Installation method (CocoaPods, Carthage, from source, etc) `CocoaPods`
* Unit testing framework (XCTest, Quick + Nimble, etc) `XCTest`
* Does your project use `.mockingbird-ignore`? `No`
* Are you using [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files)? `No`

(To be fair this could be a problem with Mockingbird, AppCenter, CocoaPods or Xcode or something in our project specifically, just wanted to see if anyone had come across it or anything similar before.)

**Comment by andrewchang-bird** [comment]
Hi Robert, it sounds like the CI might be running in a sandbox that’s preventing the dylib from loading. Please try using the [CI safe binary](https://github.com/birdrides/mockingbird/wiki/Integration-Tips) and see if that fixes it.

**Comment by ratkins** [comment]
Looks like that’s fixed it, thanks.

(I assume by “CI safe” you mean statically linked? Strange the problem presented to us as intermittent. Anyhow, I think we’re good now.)

**Comment by andrewchang-bird** [comment]
Swift Syntax isn’t possible to statically link without forking which poses lots of issues, so we bundle it in the binary text section and unbundle at runtime into a known system location (or in the same directory for CI safe binaries). This keeps the binary portable and also independent of whatever Swift toolchain is currently installed/selected on the machine. More in depth info here: #92

**Comment by ratkins** [comment]
It’s amazing you went to such lengths, I’m kind of in awe.
