### ISSUE TITLE
Guide on mocking static methods

### ISSUE THREAD

**Issue by wameson** [birdrides/mockingbird#177]
I see in Readme that mockingbird supports mocking static members.
Can you provide any sample on how to mock a static method of a class?

Thanks

**Comment by andrewchang-bird** [comment]
I’ve been working on making the static testing API a bit nicer with automatic teardown etc, but [here’s an example](https://github.com/birdrides/mockingbird/blob/5e32ad89e58315876dfb8bc56e91961f45d025f6/Tests/MockingbirdTests/Framework/GenericsTests.swift#L70) in the framework tests. The key components are:

1. A global serial queue to synchronize all interactions with static members
2. Teardown / reset static mocks prior to interacting with them (using the `staticMock` property on the mock metatype)
3. Use the concrete mock metatype, e.g. `type(of: someMock)` when stubbing or verifying

Let me know if you need additional pointers, happy to help.
