### ISSUE TITLE
Making the lib work on a CI without embedding a cisafe bin

### ISSUE THREAD

**Issue by soucolline** [birdrides/mockingbird#178]
I've been testing MockingBird to migrate from Cuckoo. Although the lib is working great and I really like the API the fact that you need to version a 35mb binary to your git (for your CI to run) is a real dealbreaker for me. I was wondering if it was something that could be changed in order not to have a `cisafe` bin or if it was a technical constraint that could not be solved ?

Great lib anyway huge thanks for the great work 👍

**Comment by andrewchang-bird** [comment]
Checking in the binary is the simplest option to pin the binary, but you can also download it or [build it from source](https://github.com/birdrides/mockingbird/wiki/Local-Development#building-from-source). For example, you could add a build phase that downloads the binary from the GitHub release artifacts (making sure to set the input and output files accordingly) which is basically what Cuckoo does.

```bash
set -eu

version = 0.16.0
curl -Lo Mockingbird-cisafe.zip "https://github.com/birdrides/mockingbird/releases/download/${version}/Mockingbird-cisafe.zip"
unzip -o Mockingbird-cisafe.zip mockingbird
```

I do agree that this could be improved a bit—either in terms of better docs or having a built-in way of pinning binaries.

**Comment by menjoo** [comment]
I use CocoaPods and got it running on CI. 

In the Test target "Generate Mockingbird Mocks" script, I had to change this:
```bash
set -e

mockingbird generate \
  --targets 'ArchitecturePlayground' \
  --outputs "${SRCROOT}/MockingbirdMocks/ArchitecturePlaygroundTests-ArchitecturePlaygroundMocks.generated.swift" \
  --support "${SRCROOT}/MockingbirdSupport"

# Ensure mocks are generated prior to running Compile Sources
rm -f '/tmp/Mockingbird-1130FD7D-40A7-4135-91F0-E30948B4CF3D'
```
To:
```bash
set -e

"${SRCROOT}/Pods/MockingbirdFramework/mockingbird" generate \
  --targets 'ArchitecturePlayground' \
  --outputs "${SRCROOT}/MockingbirdMocks/ArchitecturePlaygroundTests-ArchitecturePlaygroundMocks.generated.swift" \
  --support "${SRCROOT}/MockingbirdSupport"

# Ensure mocks are generated prior to running Compile Sources
rm -f '/tmp/Mockingbird-1130FD7D-40A7-4135-91F0-E30948B4CF3D'
```
Of course this only works if the binary was retrieved via Pods 😉

**Comment by menjoo** [comment]
> the fact that you need to version a 35mb binary to your git (for your CI to run) is a real dealbreaker for me

I use CocoaPods and exclude the `Pods` folder in `.gitignore`. So the big binary is not in source control.

**Comment by soucolline** [comment]
@menjoo thanks for the tip I'll give it a try 🙏
