### ISSUE TITLE
CI setup/automated steps

### ISSUE THREAD

**Issue by winstondu** [birdrides/mockingbird#182]
It seems really strange that the install steps are calling for adding a CLI onto the usr/bin. This seems wayyyy too complicated.

I don't understand why this package can't just be:
// package manager install step
// Run phase script to paste in.

**Comment by andrewchang-bird** [comment]
The binary installation setup is the “happy path” for Mockingbird that’s designed to be accessible to developers of all experience levels using the package managers we currently support. We’ve also found that using the CLI to streamline configuration of projects is much less error-prone than asking devs to manually modify run script phases; it’s extremely easy to end up with a broken project or even flaky tests that way.
