### ISSUE TITLE
Feature-Request: Enable calling original implementation if no stub is provided.

### ISSUE THREAD

**Issue by winstondu** [birdrides/mockingbird#185]
Sometimes, I might just want to create a version of my concrete type that is the real object, except that the invocations of functions and the get/set of properties can be verified.

From a quick overview of the architecture, this seems totally feasible. This is because mocks of concrete types are created by `Mockingbird` via subclassing that concrete type.

Currently, whenever there is no stub of the desired/function/property provided for the mock class, `fatalError(self.stubbingContext.failTest(for: invocation))` is called.

But we could also just use the actual implementation with just `super` call.

**Comment by andrewchang-bird** [comment]
Partial mocks is in the works :) Both passing the call to the superclass as well as proxying an object that conforms to the mocked type.
