### ISSUE TITLE
Module 'Mockingbird' was not compiled for testing

### ISSUE THREAD

**Issue by EvanMasterson** [birdrides/mockingbird#186]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

### Framework Bug
Module 'Mockingbird' was not compiled for testing

Installation method -> `Swift Package Manager`
Xcode version -> `12.4` 
macOS version -> `10.15.7`
mockingbird version -> `16.0`
swift --version -> `Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)`
Test Suite -> `XCTest`

#### Issue
After following installation instructions and compiling our project everything generates and builds, but when attempting to run the test suite it fails to compile with error `Module 'Mockingbird' was not compiled for testing` in the `*.generated.swift` file.
Framework was added under our 'Tests' target

![Screenshot 2021-01-11 at 11 07 18](https://user-images.githubusercontent.com/8803875/104180495-1e02c600-5405-11eb-9abd-b1d400a63fea.png)

**Comment by teejayhh** [comment]
I have exactly the same issue.

**Comment by nicholausadi** [comment]
I also experience this issue.

Any news regarding this?

**Comment by nicholausadi** [comment]
Any update regarding this issue?
I notice if I change build configuration to other than Debug will get this error

**Comment by berkus** [comment]
@andrewchang-bird hello; is there any investigation on this issue going on?

Do you need any help or reproduction scenarios/projects?

**Comment by andrewchang-bird** [comment]
Ensure that the “Enable Testability” build setting is set to **Yes** for the build configuration used by the test scheme. E.g.

<img width="1014" alt="Screen Shot 2021-07-09 at 2 34 29 PM" src="https://user-images.githubusercontent.com/47129469/125138093-dcf12300-e0c2-11eb-874b-018f94e6b8de.png">

The example project is set to use the Debug build configuration, but if your scheme uses a different build configuration for running tests (e.g. Release) then you should set that to **Yes** as well.

<img width="1272" alt="Screen Shot 2021-07-09 at 2 37 49 PM" src="https://user-images.githubusercontent.com/47129469/125138340-5852d480-e0c3-11eb-9282-1a8b898b1df0.png">

**Comment by isaac-weisberg** [comment]
Why does it even need to be @testable any way?
But yeah, I am seeing the same issue - everything seems to be connected fine, yet this import misfires. Using Cocoapods BTW.

**Comment by andrewchang-bird** [comment]
@isaac-weisberg The original intent was to separate the public testing APIs that devs use from the internal framework APIs that generated mocks use. Creating a separate module, namespacing internal APIs in an enum, or just making everything public are potential alternatives, but also come with some downsides. That said, I think adding `'ENABLED_TESTABILITY' => 'YES'` to Mockingbird’s podspec will trivially fix this issue for non-debug build configs.

**Comment by isaac-weisberg** [comment]
That did it
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # some other workarounds for other pods
            if target.name == 'MockingbirdFramework' and config.name == 'CustomDebug'
                config.build_settings['ENABLE_TESTABILITY'] = 'YES'
            end
        end
    end
end
```
But tbh, there is so much trash in our Podfile with these `post_install` routines already, and now Mockingbird enters this realm...
