### ISSUE TITLE
Unable to return custom value from function with Void return type

### ISSUE THREAD

**Issue by Kilo-Loco** [birdrides/mockingbird#2]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

In the README.md, the documentation suggests that a function that returns void like `func chirp(volume: Int)` should be able to return a custom value like true. I'm not entirely sure of the benefit for returning different types from a function, but this does not currently work.

However, if the intention is to display that an expected return type can be mocked from a function like `func chirp(volume: Int) -> Bool`, then it works as expected.

### Framework Bugs

Please provide a minimal example of your unit testing code, including any errors.

```
let bird = mock(Bird.self)
given(bird.chirp(volume: 10)) ~> true
// Binary operator '~>' cannot be applied to operands of type 'Stub<(Int) -> Void, Void>' and 'Bool'
```

## Environment

* Mockingbird CLI version: 0.6.1
* Xcode and macOS version: Xcode 11.0 (11A420a) - Mojave 10.14.5 Beta
* Swift version: 5.1
* Installation method: CocoaPods
* Unit testing framework: XCTest
* Does your project use `.mockingbird-ignore`?  No

**Comment by andrewchang-bird** [comment]
Note that the examples in the README are mainly for demonstrating the DSL and currently don’t match 1-to-1 with the minimal / stripped-down example provided in `MockingbirdTests/Example`. You’re correct that the `chirp(volume:)` method in the README is designed to return a `Bool`.

**Comment by Kilo-Loco** [comment]
Alright, I just wanted to bring this up in case it was expected behavior.
