### ISSUE TITLE
Feature request: Custom URL to download starter pack

### ISSUE THREAD

**Issue by ynx-zeissl** [birdrides/mockingbird#200]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

During installation, `mockingbird download starter-pack` should provide the possibility to enter a custom URL.
Hardcoding the url to github is not nice ;)

```
private func assetBundleUrl(for fileName: String) -> Foundation.URL {
    return Foundation.URL(string:
      "https://github.com/birdrides/mockingbird/releases/download/\(mockingbirdVersion)/\(fileName)"
    )!
  }
```

## Environment

* Mockingbird CLI version (`0.16.0`)
* Xcode `12.5.1` and macOS `11.4`
* Swift version (`5.4.2`)
* Installation method (`SPM`)
* Unit testing framework (`XCTest`)
* Does your project use `.mockingbird-ignore`? `No`
* Are you using [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files)? `No`

**Comment by ynx-zeissl** [comment]
Created a Pull request: https://github.com/birdrides/mockingbird/pull/201

**Comment by andrewchang-bird** [comment]
Added in #201

**Comment by ynx-zeissl** [comment]
Wich version do I have to download in order to get the Update? (With SPM)
Because XCode installs 0.16.0 but new Version with #201 implemented seems to be 0.16.1?

**Comment by andrewchang-bird** [comment]
It’s not yet part of a release, but you can build and install the CLI changes by pulling master running `make install`.

**Comment by ynx-zeissl** [comment]
When I do all the commands from the install instructions, but change the package in XCode's SPM from `0.16.0` to `master` and follow the commands then, I first get an error on the `make install` instruction:
```
error: invalid access to /Users/myUser/Library/Developer/Xcode/DerivedData/myProject/SourcePackages/checkouts/mockingbird/Sources/Package.resolved
make: *** [build-cli] Error 1
```

When I execute it one more time, it installs everything correctly.
```
[27/27] Build complete!
# Inject custom rpath into binary.
install_name_tool -delete_rpath "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx" "/Users/myUser/Library/Developer/Xcode/DerivedData/myProject/SourcePackages/checkouts/mockingbird/Sources/.build/x86_64-apple-macosx/release/mockingbird"
install_name_tool -add_rpath "/var/tmp/mockingbird/0.16.1/libs" "/Users/myUser/Library/Developer/Xcode/DerivedData/myProject/SourcePackages/checkouts/mockingbird/Sources/.build/x86_64-apple-macosx/release/mockingbird"
install -d "/usr/local/bin"
install: chmod 755 /usr/local/bin: Operation not permitted
install "/Users/myUser/Library/Developer/Xcode/DerivedData/myProject/SourcePackages/checkouts/mockingbird/Sources/.build/x86_64-apple-macosx/release/mockingbird" "/usr/local/bin"
```

Afterwards, when I try to download the starter-pack, I get:

```
mockingbird download starter-pack
Downloading asset bundle from https://github.com/birdrides/mockingbird/releases/download/0.16.1/MockingbirdSupport.zip
Temporary asset bundle data stored at file:///var/folders/v1/hbvmpvgn3h3b4nmj5qbjjjyxc61gfk/T/CFNetworkDownload_lbgkPN.tmp
Extracting downloaded asset bundle to /Users/myUser/Development/main/apps/ios/myProject
error: The downloaded asset bundle is corrupted
```

This also happens when I enter a custom `--url` of course, but why is there no starter-pack with version 0.16.1 available?
Or don't I even need the starter-pack when using `make install` instead of `make install-prebuilt` ?

**Comment by andrewchang-bird** [comment]
The first error is likely because the environment wasn’t initially [bootstrapped for local development](https://github.com/birdrides/mockingbird/wiki/Local-Development). The second is because there isn’t an active 0.16.1 release in the birdrides repo, so the URL points to GitHub’s 404 page.

**Comment by ynx-zeissl** [comment]
When will there an official release with this fix?

**Comment by andrewchang-bird** [comment]
I’m aiming to push out 0.17.0 by the end of this week.
