### ISSUE TITLE
Failure to decode project description generated by `swiftpm`.

### ISSUE THREAD

**Issue by kielgillard** [birdrides/mockingbird#214]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

Mockingbird cannot parse the json description of my Swift package.
```
error: keyNotFound(CodingKeys(stringValue: "dependencies", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "targets", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"dependencies\", intValue: nil) (\"dependencies\").", underlyingError: nil))
```

[redacted-desc.json.zip](https://github.com/birdrides/mockingbird/files/6845898/redacted-desc.json.zip) (I redacted some local paths).

```bash
mockingbird generate --project redacted-desc.json --target CompanyTextInput --support MockingbirdSupport 
```

## Environment
0.16.0 / Big Sur / Installed with Swift Package Manager / XCTest / Uses .mockingbird-ignore / Uses supporting files

Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
Target: x86_64-apple-darwin20.5.0

* Mockingbird CLI version (`mockingbird version`)
* Xcode and macOS version (are you running a beta?)
* Swift version (`swift --version`)
* Installation method (CocoaPods, Carthage, from source, etc)
* Unit testing framework (XCTest, Quick + Nimble, etc)
* Does your project use `.mockingbird-ignore`?
* Are you using [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files)?

**Comment by kielgillard** [comment]
Ultimately, I'm trying to generate mocks the sources of my package for the package tests. I do not have an Xcode project.

**Comment by andrewchang-bird** [comment]
Thanks for reporting. Originally when JSON project descriptions were added in #171 the intent was to upstream some changes to SPM, but it looks like they’ve since added `target_dependencies` as part of the project description output. It should be a minor change to get this to work.

It’s not ideal, but as a workaround in the meantime you can manually generate and then modify each target to include `dependencies`.

**Comment by kielgillard** [comment]
Thanks! Works a treat. I also get the following decoding error with this JSON, too:
```
error: keyNotFound(CodingKeys(stringValue: "dependencies", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "targets", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1)], debugDescription: "No value associated with key CodingKeys(stringValue: \"dependencies\", intValue: nil) (\"dependencies\").", underlyingError: nil))
```

Target in question:
```
    {
      "c99name" : "KeychainAdditions",
      "module_type" : "SwiftTarget",
      "name" : "KeychainAdditions",
      "path" : "Sources/KeychainAdditions",
      "product_memberships" : [
        "KeychainAdditions"
      ],
      "sources" : [
        "AppleCredentialStorageService.swift",
        "KeychainItem.swift"
      ],
      "type" : "library"
    }
```

Post-processing the JSON description for this target with `dependencies: []` works as expected and generates the mocks.

**Comment by kielgillard** [comment]
@andrewchang-bird in my adventures I see that `swift package describe --type json` and `swift package dump-package` [produce inconsistent results](https://bugs.swift.org/browse/SR-14972), where the describe command does not include target dependencies. The PR I submitted increases Mockingbird's dependency on the describe command. Should I submit a PR to parse JSON from `dump-package` instead?

**Comment by kielgillard** [comment]
Submitted https://github.com/birdrides/mockingbird/pull/216
