### ISSUE TITLE
Flattened inherited type is missing rawInheritedTypes

### ISSUE THREAD

**Issue by alvarhansen** [birdrides/mockingbird#22]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

We have case where **empty** `InitializerProxy` enum is generated for mock type. This creates mock type that can't be initialized.

The source setup is basically this:

**MyVC.swift**
```
import UIKit

class MyVC: UIViewContoller: MyProtocol2 {}
```

**MyProtocol2.swift**
```
protocol MyProtocol2: MyProtocol1 {}
```

**MyProtocol1.swift**
```
import Foundation
protocol MyProtocol1: AnyObject {}
```

It seems to be caused by `ParseFilesOperation` excluding dependencies parsing: https://github.com/birdrides/mockingbird/blob/78707c9544d78535e68223e46fabdbb07b1ae3ab/MockingbirdGenerator/Parser/Operations/ParseFilesOperation.swift#L146
&
https://github.com/birdrides/mockingbird/blob/78707c9544d78535e68223e46fabdbb07b1ae3ab/MockingbirdGenerator/Parser/Operations/ParseFilesOperation.swift#L115
which causes flattened inherited types to not find its referenced types if they come from other frameworks.

https://github.com/birdrides/mockingbird/blob/78707c9544d78535e68223e46fabdbb07b1ae3ab/MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift#L67
referencing search from
https://github.com/birdrides/mockingbird/blob/78707c9544d78535e68223e46fabdbb07b1ae3ab/MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift#L41

My current workaround hack was to ignore `shouldMock` flag and parse all files:
https://github.com/birdrides/mockingbird/blob/78707c9544d78535e68223e46fabdbb07b1ae3ab/MockingbirdGenerator/Parser/Operations/ParseFilesOperation.swift#L115
Is there any particular reason why not all files are being parsed? Just optimisation?

**Comment by andrewchang-bird** [comment]
Thanks for reporting, Alvar. A few questions:

1. In your example are `MyProtocol1` and `MyProtocol2` in the same module as `MyVC`?
2. Are you including the default [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files) for `UIViewController`?

**Comment by alvarhansen** [comment]
1. No. `MyVC.swift` and `MyProtocol2.swift` are in one framework and `MyProtocol1.swift` in separate framework.
2. Yes, the supporting files are included and are working for other mocked types in this framework.

The issue seems to be that `MyVC.swift` and `MyProtocol2.swift` do not import Foundations, and because of that Swift Foundation support is never used when resolving inherited types at https://github.com/birdrides/mockingbird/blob/78707c9544d78535e68223e46fabdbb07b1ae3ab/MockingbirdGenerator/Parser/Operations/FlattenInheritanceOperation.swift#L111

**Comment by andrewchang-bird** [comment]
This should be fixed in the latest version (0.9.0) by #19. Can you update and see if that solves it?

**Comment by alvarhansen** [comment]
Yes, i am using latest commit. I was able to create project where this bug reproduces:
https://github.com/alvarhansen/mockingbird/commit/62b68896784bbc602464c992a8036e10e2fde156

MyFramework2 demonstrates the bug and MyFramework3 shows how it should work.

In `MyFramework2Mocks.generated.swift` `ViewModelView2Mock` has empty
[`InitializerProxy`](https://github.com/alvarhansen/mockingbird/commit/62b68896784bbc602464c992a8036e10e2fde156#diff-70a7330ad845f434f9eefe5fd5778901R33) which is incorrect. Instead it should have
[`fileprivate init(sourceLocation: Mockingbird.SourceLocation)`](https://github.com/alvarhansen/mockingbird/commit/62b68896784bbc602464c992a8036e10e2fde156#diff-6aaead8a1da76f5bf6a3f90e61f82095R32) as can
be seen in `MyFramework3Mocks.generated.swift`

**Comment by andrewchang-bird** [comment]
Thanks! Definitely similar to the previous issue you found except across modules (versus files within the same module).
