### ISSUE TITLE
'mock' is unavailable

### ISSUE THREAD

**Issue by Allje** [birdrides/mockingbird#221]
## Description

I have created a test project in Xcode to have a look at the Mockingbird framework

The file that i'm testing is this one [_TestFile.swift_]:
```
import Foundation

protocol Bird {
    var canFly: Bool { get }
    func fly()
}

class Tree {
    let bird: Bird
    
    init(with bird: Bird) {
        self.bird = bird
    }
    
    func shake() {
        guard bird.canFly else { return }
        bird.fly()
    }
}
```

and I have created following test class [_MockingbirdExampleTests.swift_]:
```
import XCTest
import Mockingbird
@testable import MockingbirdExample

class MockingbirdExampleTests: XCTestCase {
    func testExample() throws {
        let bird = mock(Bird.self)  // Protocol mock
        
        // This is an example of a functional test case.
        // Use XCTAssert and related functions to verify your tests produce the correct results.
    }
}
```
 
My pod file contains following (MockingbirdFramework is version 0.17.0): 
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MockingbirdExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MockingbirdExample

  target 'MockingbirdExampleTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'MockingbirdFramework'
  end

  target 'MockingbirdExampleUITests' do
    # Pods for testing
  end
end
```

My problem is that I get this error in the _MockingbirdExampleTests.swift_ when creating the bird mock ( let bird = mock(Bird.self) ) :
**'mock' is unavailable: No generated mock for this type which might be resolved by building the test target (⇧⌘U)**

I have tried to build the for testing (⇧⌘U) and have restarted Xcode, without any success.
## Environment
* Xcode and macOS version: Xcode 12.5.1, macOS 11.5.1
* Swift version: 5.4.2
* Installation method: CocoaPods
* Unit testing framework: XCTest
* Does your project use `.mockingbird-ignore`: No
* Are you using [supporting source files]: No

**Comment by andrewchang-bird** [comment]
Assuming you went through the standard setup guide and configured the test target with `mockingbird install`, can you confirm that the `.generated.swift` mock file is being created when you build the test bundle? (See also the [Troubleshooting Guide](https://github.com/birdrides/mockingbird/wiki/Troubleshooting).)

If possible, please upload or push the test project.

**Comment by Allje** [comment]
I had overlooked the steppe with configuration of the test target (mockingbird install). Now it works on my local machine.
Next step is to get it working in out CI environment which is Azure DevOps. I guess that the configuration of the test target there has to happend after the pods has been installed and before the tests are executed. Do you have and expirence/ideas on how to accomplise that. Today we are using the Xcode task Xcode@5 to build and test our software.

**Comment by andrewchang-bird** [comment]
You only need to configure the test target once and check those changes in, assuming you’re not using a project generator like XcodeGen. It should also work out-of-the-box in CI environments, but for advanced options and setups here’s a wiki page with more info: https://github.com/birdrides/mockingbird/wiki/Manual-Setup

**Comment by Allje** [comment]
Thanks. I got it working now.
