### ISSUE TITLE
Mocking a protocol I another project

### ISSUE THREAD

**Issue by Allje** [birdrides/mockingbird#223]
I have a Xcode workspace that includes two Xcode projects. The structure following

![Mockingbird](https://user-images.githubusercontent.com/88710682/130217018-80a1b89a-1487-4675-91e2-12ba899a822a.png)

I can install mockingbird for DeviceA with following command:
_**iOSApplication/DeviceA$ mockingbird install -- target DeviceATests --source DeviceA**_

The problem is that DeviceA uses a protocol (ProtocolA) defined in the common folder and I can't install mockingbird for that interface.
I have tried with following command
_**iOSApplication/DeviceA$ mockingbird install -- target DeviceATests --source ../Common/Common**_
but I get this error:
_**malformedConfiguration(description: "Unable to find source target named \'../Common/Common\'")**_

I have also tried to use a absolute path to Common, but that also doesn't work.
Is it not possible to mock a file from another project?

## Environment

* Mockingbird CLI version (`mockingbird version`): 0.17.0
* Xcode and macOS version (are you running a beta?): Xcode: 12.5.1, macOS: 11.5.2 
* Swift version (`swift --version`): Apple Swift version 5.4.2
* Installation method (CocoaPods, Carthage, from source, etc): CocoaPods
* Unit testing framework (XCTest, Quick + Nimble, etc): XCTest
* Does your project use `.mockingbird-ignore`? No
* Are you using [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files)? No

**Comment by andrewchang-bird** [comment]
You can modify the configured build phase (or manually add another one) to invoke the generator with the `--project` option.

* https://github.com/birdrides/mockingbird/wiki/Manual-Setup
* https://github.com/birdrides/mockingbird#generate
