### ISSUE TITLE
NSInvalidArgumentException

### ISSUE THREAD

**Issue by jdschin** [birdrides/mockingbird#233]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description
The test is failing due to:
`*** -[NSProxy methodSignatureForSelector:] called! (NSInvalidArgumentException)`

Im having:
```
class Service {
  func test(vc: UIViewController) {}
}
```

And want to stub the service like this:
`given(service.test(vc: any()))`

The result is:
`TreeTests.testDroppingLargeFruit_doesNothing(): *** -[NSProxy methodSignatureForSelector:] called! (NSInvalidArgumentException)`

## Environment

* Mockingbird CLI version (`0.18.1`)
* Xcode and macOS version: Xcode 12.5.1 and 13,OSX 11.4
* Swift version: Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
* Installation method: CocoaPods
* Unit testing framework: XCTest
* Does your project use `.mockingbird-ignore`? No
* Are you using [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files)? No

**Comment by JaroVoltix** [comment]
@jdschin Any success with this? I have the same issue

**Comment by jdschin** [comment]
Hey @JaroVoltix. Its working when you pass in an actual UIViewController instance instead of any()

This worked for me as a workaround:

`given(service.test(vc: UIViewController()))`

**Comment by JaroslawItcraft** [comment]
Thank @jdschin 
However is this working when I want to verify if this method was called with any parameter not that exact instance of UIViewController?

**Comment by AlexanderMarchant** [comment]
@JaroslawItcraft Same issue here. Changing `any()` to `notNil()` in the seems to fix it.

`verify(self.mockUserNotificationCenter.add(notNil(), withCompletionHandler: any())).wasCalled(1)`

**Comment by pedroatanasio** [comment]
Same problem here. This problem makes it impossible to use a custom matcher when the parameter is an ObjC class.

Given this signature:

`func evaluateLocation(loc: CLLocation) `

The following assertion cannot be done:

`verify(mock.evaluateLocation(loc: any(where: { isInside(location: $0, region: region) }))).wasCalled()`

It is working correctly with Swift classes
