### ISSUE TITLE
Unable to verify initializer since 0.18.0

### ISSUE THREAD

**Issue by myihsan** [birdrides/mockingbird#240]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

I depend on the implementation below in a special case.

https://github.com/birdrides/mockingbird/blob/13ee8ab4346bf65c51612305a897dffcfab45e5c/Sources/MockingbirdGenerator/Generator/Templates/InitializerMethodTemplate.swift#L76-L82

But it has been deleted by #217.

Do we have to delete it for supporting partial mocks, or it's deleted unintentionally?

**Comment by andrewchang-bird** [comment]
Can you provide an example of how you’re using this initializer in tests? It should still be generating this initializer variant (or at least that was the intention):

https://github.com/birdrides/mockingbird/blob/6a682afc667313cc2609d10ca871b819c02105f9/Sources/MockingbirdGenerator/Generator/Templates/InitializerMethodTemplate.swift#L58-68

**Comment by myihsan** [comment]
Sorry for the late reply.
I am testing something like below.
```swift
protocol SomeProtocol: RawRepresentable {
    // some requirement
}

class SomeTest: XCTestCase {
    func testCreatation() {
        let object = SomeCreator<SomeProtocolMock<Int>>.create()
        verifyRawValueInitCalled(on: object, with: -1)
    }

    private func verifyRawValueInitCalled<RawValue: Equatable>(on object: SomeProtocolMock<RawValue>, with rawValue: RawValue) {
        let invocation: Invocation = Invocation(selectorName: "init?(`rawValue`: RawValue) ", arguments: [ArgumentMatcher(rawValue)], returnType: Swift.ObjectIdentifier((Void).self))
        let declaration = Mockingbird.Mockable<Mockingbird.PropertyGetterDeclaration, () -> SomeProtocolMock<RawValue>, SomeProtocolMock<RawValue>>(mock: object, invocation: invocation)
        verify(declaration).wasCalled()
    }
}
```
It works before 0.18.0, but I only get an empty initializer since 0.18.0.

**Comment by andrewchang-bird** [comment]
Got it, thanks for the code snippet.

I removed the initializer invocation recording in 0.18 as there isn’t an official way of calling `verify` on those declaration (you’re essentially using internal APIs here). I can see some value in asserting how objects are initialized, although it definitely is uncommon.

I’ll have to think a bit about how to design an official API for this—it’ll probably end up using a synthetic declaration on the instance similar to the legacy property getters and setters. I can’t guarantee I can prioritize it for the next release though. If you’re interested in adding the feature (should be a medium-sized task) let me know and I can walk you through it.

```swift
verify(myMock.init(some: arg)).wasCalled()
```

**Comment by myihsan** [comment]
> although it definitely is uncommon.

I totally agree with you.

> If you’re interested in adding the feature (should be a medium-sized task) let me know and I can walk you through it.

I would love to, but I may be active only at weekends and using some time to catch up on the latest implementations.
Do you think that's okay?

**Comment by andrewchang-bird** [comment]
> I would love to, but I may be active only at weekends and using some time to catch up on the latest implementations. Do you think that's okay?

Yes, for sure! We’re happy with whatever you’re comfortable contributing. Note that we currently use Slack for coordinating, but let me know if another option works better for you.
