### ISSUE TITLE
Not all mocks generated

### ISSUE THREAD

**Issue by Allje** [birdrides/mockingbird#241]
## Description

I have configured the test target with following command
mockingbird install --project MyDevice.xcodeproj --source MyDevice --target MyDeviceTests

In Xcode I can see that following is inset in the build phase for the test target:
_mockingbird generate \
  --targets 'MyDevice' \
  --outputs "${SRCROOT}/MockingbirdMocks/MyDeviceTests-MyDeviceMocks.generated.swift"_

The file "MyDeviceTests-MyDeviceMocks.generated.swift" generated from Xcode is **46 KB**

The problem is that a mock isn't generated for all protocols

If I run following command from the terminal

_mockingbird generate --targets 'MyDevice' --outputs "MyDevice/MockingbirdMocks/MyDeviceTests-MyDeviceMocks.generated.swift"_

then all mock is generated for all protocols and the "MyDeviceTests-MyDeviceMocks.generated.swift" generated is **262 KB**

Why is there a difference?

## Environment
* Mockingbird CLI version (`mockingbird version`): 0.17.0
* Xcode and macOS version (are you running a beta?): Xcode 12.5.1, macOS 11.6
* Swift version (`swift --version`): 5.4.2
* Installation method (CocoaPods, Carthage, from source, etc): CocoaPods
* Unit testing framework (XCTest, Quick + Nimble, etc): XCTest
* Does your project use `.mockingbird-ignore`? No
* Are you using [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files)? No

**Comment by andrewchang-bird** [comment]
Likely due to thunk pruning, which by default is set to `omit`. More info: https://github.com/birdrides/mockingbird#thunk-pruning
