### ISSUE TITLE
SwiftLint generates many warnings for generated files

### ISSUE THREAD

**Issue by AccuPhoenix01** [birdrides/mockingbird#255]
## New Issue Checklist

- [ X] I updated my Mockingbird framework and CLI to the latest version
- [ X] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

Mockingbird generated files break rules of our SwiftLint setup, AND I can't find a way to exclude the `Generated Mocks` folder from SwiftLint rules because the space in the name can't be escaped out. I tried multiple ways of trying to exclude the folder or the individual mock files, to no avail. One solution might be to change the name of the folder to `Generated_Mocks` or `GeneratedMocks`, or to put a comment at the top of every generated file to ignore Swiftlint `// swiftlint:disable ...` 
Thank you for your time.

### Generator Bugs

If the generator produces code that is malformed or does not compile, please provide:

1. A minimal example of the original source
2. The actual mocking code generated
3. The expected mocking code that should be generated (or a description)

/Users/paveglioc/Dev/Apps-FlagshipMobile-iOS/MockingbirdMocks/AccuWeatherTests-AccuWeatherMocks.generated.swift:4622:5: Implicit Getter Violation: Computed read-only properties should avoid using the get keyword. (implicit_getter)
Redundant Void Return Violation: Returning Void in a function declaration is redundant. (redundant_void_return)

![image](https://user-images.githubusercontent.com/46455562/148290085-d1036133-e3c4-4bd3-957b-547b4f8cf7cd.png)

## Environment

* Mockingbird CLI version (`mockingbird version`)
* ?
* Xcode and macOS version (are you running a beta?)
* Mac OS Big Sur 11.6.2, Xcode 13.2.1
* Swift version (`swift --version`)
* 5.5.2
* Installation method (CocoaPods, Carthage, from source, etc)
* CocoaPods
* Unit testing framework (XCTest, Quick + Nimble, etc)
* XCTest
* Does your project use `.mockingbird-ignore`?
* I don't think so
* Are you using [supporting source files](https://github.com/birdrides/mockingbird#supporting-source-files)?

**Comment by andrewchang-bird** [comment]
You can pass `--disable-swiftlint` as a [generator option](https://github.com/birdrides/mockingbird#generate) or when configuring the test target to silence these warnings. Alternatively, supply custom header lines with `--header Line1 Line2 ...`.

Note that generated mocks don’t actually end up in a folder called `Generated Mocks`, but rather the [default behavior](https://github.com/birdrides/mockingbird#--outputs) is to output into `$(SRCROOT)/MockingbirdMocks`.
