### ISSUE TITLE
Generator should support mocking methods from parent class

### ISSUE THREAD

**Issue by juyan** [birdrides/mockingbird#269]
## New Feature Request Checklist

- [ X ] I searched the [existing GitHub feature requests](https://github.com/birdrides/mockingbird/labels/enhancement)

## Overview

It looks like generate mocks does not support parent class's methods.

## Example

Swift Package "Base":
```
open class BaseClass {
    public func getBaseVersion() -> Int
}
```

Swift Package "Middle":
```
import Base

public class MiddleClass: BaseClass {
    public func getMiddleVersion() -> Int
}
```

Now run mockingbird on package `Middle` with the following command. Note that we have copied `BaseClass.swift` under the `MockingbirdSupport` folder.

```
mockingbird generate --project project.json --output-dir Tests/MiddleTests --targets Middle --support ~/Downloads/MockingbirdSupport
```

Note that in the generated mock file, only `getMiddleVersion` is mocked, but not `getBaseVersion`.

## Expected

The generate mock should also support mocking method `getBaseVersion`.

**Comment by andrewchang-bird** [comment]
This is something that’s supported, so it sounds like your Mockingbird support configuration has some issues.

- Is `BaseClass.swift` in a directory that matches the module name? In your example that would be `Base`.
- Does the file declaring `MiddleClass` explicitly import `Base`?

**Comment by juyan** [comment]
> Is BaseClass.swift in a directory that matches the module name? In your example that would be Base.
Yes

> Does the file declaring MiddleClass explicitly import Base?
Yes

> Do you get any diagnostic errors or warnings if you include --diagnostics all? The generator will complain if you’re inheriting from a type it doesn’t know about.
No errors got.

@andrewchang-bird 
Please checkout my source code [here](https://github.com/juyan/mockingbird-test/tree/master/Middle). Not sure why it is not working as expected.

**Comment by andrewchang-bird** [comment]
Thanks for providing the repo. Since class mocks rely on subclassing and `Base` is defined a separate module, `getBaseVersion` needs to be `open` instead of `public`.

**Comment by juyan** [comment]
Thanks @andrewchang-bird
