### ISSUE TITLE
Use PRODUCT_NAME not productName

### ISSUE THREAD

**Issue by paiv** [birdrides/mockingbird#28]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

When `PRODUCT_MODULE_NAME` not specified, use `PRODUCT_NAME` from build settings to infer module name.
Target's `productName` is a different thing, and should not be used.

https://github.com/birdrides/mockingbird/blob/c80b79fee8612814b6d3b399d7fac3be5dc6f926/MockingbirdGenerator/Parser/Cache/CodableTarget.swift#L136

For example:
- create new project in Xcode
- pick and rename a target
- target's `productName` stays unchanged

[project.zip](https://github.com/birdrides/mockingbird/files/4102907/project.zip)

## Environment

* Mockingbird CLI version `0.9.0`
* Xcode `11.3` and macOS `10.15.2`
* Swift version `Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)`

**Comment by andrewchang-bird** [comment]
Issue is still occurring in `0.10.0`.
