### ISSUE TITLE
Exception on line with given on MacOS 13.2 and XCode 14.2

### ISSUE THREAD

**Issue by chrizstone** [birdrides/mockingbird#322]
I have the problem that I get an exception when try to stub methods with the given function. Same code works on older machines with older MacBooks.

Is there a known issue?

![Bildschirm­foto 2023-01-25 um 13 57 24](https://user-images.githubusercontent.com/5380618/214569196-8d7d16e8-03f8-43dd-bf68-03a9ea97eb24.png)

**Comment by chadgames** [comment]
I am also having the same issue; M1 Pro, MacOS 13.2.1, Xcode 14.2, SPM v 0.20.0

Was this resolved?

**Comment by rivera-ernesto** [comment]
We are having the same issue. Can you explain how you solved it @chrizstone ? Or why this was closed?

**Comment by lux2704** [comment]
I'm having the same issue ... anyone ?
