### ISSUE TITLE
'mock' is unavailable when mocking public protocols from other module

### ISSUE THREAD

**Issue by adeds** [birdrides/mockingbird#333]
## New Issue Checklist

- [x] I updated the framework and generator to the latest version
- [x] I searched the [existing GitHub issues](https://github.com/birdrides/mockingbird/issues) and list of [common problems](https://mockingbirdswift.com/common-problems)

## Overview

cannot mock protocol from other module

## Example

in module A
```
public protocol AsdfProtocolTwo {
    func something() -> Int
}

class AsdfInteractorTwo: AsdfProtocolTwo {
    func something() -> Int {
        return 0
    }
}
```

from module B
```
var asdfTwo = mock(AsdfProtocolTwo.self) // 'mock' is unavailable: No generated mock for this type; try building the test target (⇧⌘U) to generate mocks
```
If the generator is not producing code or crashing, please provide the build logs.

## Expected Behavior

is my implementation false or this error is expected (we can not mock protocol from other module)

If needed, provide a short description of how it should work.

## Environment

* Mockingbird CLI version (`mockingbird version`) = 0.19.0
* Xcode and Swift version (`swift --version`) = swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: x86_64-apple-macosx14.0
* Package manager (CocoaPods, Carthage, SPM project, SPM package) = SPMPackage
* Unit testing framework (XCTest, Quick/Nimble) = XCTest
* Custom configuration
  - [ ] Mockingbird ignore files
  - [ ] Supporting source files

**Comment by dcramps** [comment]
https://mockingbirdswift.com/mocking-external-types

**Comment by adeds** [comment]
> https://mockingbirdswift.com/mocking-external-types

thank youuuu @dcramps
