### ISSUE TITLE
Mocked targets with dashes do not compile

### ISSUE THREAD

**Issue by Daedren** [birdrides/mockingbird#7]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

If you mock a target with a dash in its name, such as “TestTarget-iOS”, the generated mocks from Mockingbird will not compile.

This is because targets with dashes must be imported and accessed with an underscore instead.
e.g. “import TestTarget_iOS”

```bash
$ mockingbird install —targets App-iOS —destination App-iOSTests
Installed Mockingbird to `App-iOSTests` in /Users/daedren/git/appiOS/appiOS.xcodeproj
```

## Environment

* Mockingbird CLI version (`mockingbird version`)
0.7.0
* Xcode and macOS version (are you running a beta?)
Xcode 11.1
macOS 10.14.4
* Swift version (`swift --version`)
Swift 5.1
* Installation method (CocoaPods, Carthage, from source, etc)
CocoaPods
* Unit testing framework (XCTest, Quick + Nimble, etc)
XCTest
* Does your project use `.mockingbird-ignore`?
It does not

**Comment by andrewchang-bird** [comment]
Should be fixed in #10
