### ISSUE TITLE
Ambiguous use of operator '~>' while stubbing methods without parameter

### ISSUE THREAD

**Issue by seven332** [birdrides/mockingbird#85]
## New Issue Checklist

- [x] I updated my Mockingbird framework and CLI to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/birdrides/mockingbird/issues)

## Description

The `Ambiguous use of operator '~>'` error pops up while stubbing methods without parameter using a closure.

### Framework Bugs

Bird.swift
```swift
import Foundation

public protocol Bird {
  func fly()
}
```

BirdTests.swift
```swift
class TreeTests: XCTestCase {

  var bird: BirdMock!

  override func setUp() {
    bird = mock(Bird.self)
  }

  func testStubFly() {
    given(bird.fly()) ~> { print("fly") } // ⚠️ Ambiguous use of operator '~>'
  }
}
```

I think it matches these two methods.
``` swift
public func ~> <I, R>(stub: Stub<I, R>, implementation: @escaping () -> R) {
  addStub(stub, implementation: implementation)
}

public func ~> <I, R>(stub: Stub<I, R>, implementation: I) {
  addStub(stub, implementation: implementation)
}
```

## Environment

* Mockingbird CLI version `0.11.0`
* Xcode `11.4` and macOS version `10.15.4`
* Swift version `Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)`
* Installation method `CocoaPods`
* Unit testing framework `XCTest`
* Does your project use `.mockingbird-ignore`? `No`

**Comment by andrewchang-bird** [comment]
Thanks for reporting! Unfortunately it doesn’t look like there’s a great workaround for this issue. Will remove the convenience non-autoclosure stubbing operator for `0.12.0`.
