### ISSUE TITLE
MyTypeMock does not conform to protocol NSObjectProtocol

### ISSUE THREAD

**Issue by ferehsteh** [birdrides/mockingbird#97]
Hi,

In my project, there are supporting source files related to NSObjectProtocol. but the error "**MyTypeDelegateMock does not conform to protocol NSObjectProtocol**" is not resolved.

**protocol DTPhotoViewerControllerDelegate: NSObjectProtocol {
}
protocol MyTypeDelegate: DTPhotoViewerControllerDelegate {
}**

In **MyProjectMocks.generated.swift** file, i have this error:

**// MARK: - Mocked MyTypeDelegate**

**public final class MyTypeDelegateMock: MyProject.MyTypeDelegate, Mockingbird.Mock {
}**

**Comment by andrewchang-bird** [comment]
Is `DTPhotoViewerControllerDelegate` an externally defined type (e.g. from a third-party library or framework)?

**Comment by ferehsteh** [comment]
Thanks for your response :)
Yes. It is an external library.

**Comment by andrewchang-bird** [comment]
Try adding a supporting source file for `DTPhotoViewerControllerDelegate` e.g. create a file at `MockingbirdSupport/DTPhotoViewer/DTPhotoViewerControllerDelegate.swift` with the contents:

```swift
protocol DTPhotoViewerControllerDelegate: NSObjectProtocol {}
```

**Comment by ferehsteh** [comment]
I created a file as the same as you mentioned but in the path:
`MockingbirdSupport/Foundation/DTPhotoViewerControllerDelegate.swift`
But this error is not fixed.

I will try to change the path. 
Thanks.

**Comment by ferehsteh** [comment]
> Try adding a supporting source file for `DTPhotoViewerControllerDelegate` e.g. create a file at `MockingbirdSupport/DTPhotoViewer/DTPhotoViewerControllerDelegate.swift` with the contents:
> 
> ```swift
> import Foundation
> 
> protocol DTPhotoViewerControllerDelegate: NSObjectProtocol {}
> ```

Unfortunately, it didn't work :(
Do you have any other suggestions?

**Comment by andrewchang-bird** [comment]
Oh, looks like the issue might be that the access level wasn’t public. (Also make sure that you’re importing `Foundation` in supporting source file or the linker won’t work.)

```swift
import Foundation

public protocol DTPhotoViewerControllerDelegate: NSObjectProtocol {}
```

**Comment by ferehsteh** [comment]
I have done all steps but it does not work :(
I attached required files.

<img width="1325" alt="Screen Shot 2020-04-26 at 3 43 05 PM" src="https://user-images.githubusercontent.com/5345361/80306703-21541400-87da-11ea-8ad5-98825ec7dbae.png">

<img width="350" alt="Screen Shot 2020-04-26 at 3 38 56 PM" src="https://user-images.githubusercontent.com/5345361/80307037-f074de80-87db-11ea-9b50-56b1d238c7fb.png">

<img width="500" alt="Screen Shot 2020-04-26 at 4 30 09 PM" src="https://user-images.githubusercontent.com/5345361/80306933-5ca31280-87db-11ea-9600-4632e37e6fda.png">

[Build Bellchat_2020-04-26T15-13-07-.txt](https://github.com/birdrides/mockingbird/files/4535254/Build.Bellchat_2020-04-26T15-13-07-.txt)

**Comment by andrewchang-bird** [comment]
Ok, so since the module name for that library is actually `DTPhotoViewerController`, the supporting source file should be under `MockingbirdSupport/DTPhotoViewerController` instead. Sorry for the confusion here.

**Comment by ferehsteh** [comment]
It is fixed :)
Thanks a lot.

**Comment by andrewchang-bird** [comment]
Awesome! Closing this issue.
